In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
from google.colab import files
upload=files.upload()

Saving UniversalBank.csv to UniversalBank (4).csv


Variables definition

ID - Customer ID

Age - Customer's age in completed years

Experience - Number of years of professional experience.

Income - Annual income of the customer (in $ 1000).

ZIPCode - Home Address ZIP code.

Family - Family size of the customer

CCAvg - Avg. spending on credit cards per month - in thousands usd

Education - Education Level. 1: Undergrad; 2: Graduate; 3: Advanced/Professional

Mortgage - Value of house mortgage if any - in thousands usd

Personal Loan - Did this customer accept the personal loan offered in the last campaign?

Securities Account - Does the customer have a securities account with the bank?

CD Account - Does the customer have a certificate of deposit (CD) account with the bank?

Online - Does the customer use internet banking facilities?

CreditCard - Does the customer uses a credit card issued by UniversalBank?

In [ ]:
data = pd.read_csv("UniversalBank.csv")
data.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [ ]:
data.columns

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'Personal Loan', 'Securities Account',
       'CD Account', 'Online', 'CreditCard'],
      dtype='object')

In [ ]:
x = data.iloc[:, 1:13].values # no id column
y = data.iloc[:, -1].values

In [ ]:
x

array([[25.,  1., 49., ...,  1.,  0.,  0.],
       [45., 19., 34., ...,  1.,  0.,  0.],
       [39., 15., 11., ...,  0.,  0.,  0.],
       ...,
       [63., 39., 24., ...,  0.,  0.,  0.],
       [65., 40., 49., ...,  0.,  0.,  1.],
       [28.,  4., 83., ...,  0.,  0.,  1.]])

In [ ]:
y

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state = 42)

The Radial Basis Function (RBF) kernel is a kernel function used in Support Vector Machine (SVM) classifiers.

It's a popular choice for SVMs because of its flexibility and ability to capture complex relationships between the input and output variables

In practice, SVM algorithm is implemented using a `kernel`. It uses a technique called the `kernel trick`.

 In simple words, a `kernel` is just a function that maps the data to a higher dimension where data is separable

 the kernel trick helps us to build a more accurate classifier

 In the context of SVMs, there are 4 popular kernels

  – `Linear kernel`, `Polynomial kernel` and `Radial Basis Function (RBF) kernel` (also called Gaussian kernel) and `Sigmoid kernel`.

In [ ]:
from sklearn.svm import SVC

classifier = SVC(kernel = 'rbf', random_state = 0)
# kernel - 'linear', 'poly', 'rbf', 'sigmoid
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[889   0]
 [361   0]]


In [ ]:
accuracy_score(y_test, y_pred)

0.7112

The parameter C in SVM helps control the trade-off between the training error and the margin

To be specific, a smaller value of C allows for a larger margin, potentially leading to more misclassifications on the training data.

On the other hand, a larger value of C puts more emphasis on minimizing the training error

outliers can be reduced

Default hyperparameter means C=1.0,  kernel=`rbf`

In [ ]:
# import SVC classifier
from sklearn.svm import SVC
# import metrics to compute accuracy
from sklearn.metrics import accuracy_score

# instantiate classifier with default hyperparameters
svc=SVC()

# fit classifier to training set
svc.fit(X_train,y_train)

# make predictions on test set
y_pred=svc.predict(X_test)

# compute and print accuracy score
print('Model accuracy score with default hyperparameters: ',accuracy_score(y_test, y_pred))

Model accuracy score with default hyperparameters:  0.7112


accuracy depends on data set

In [ ]:
# instantiate classifier with rbf kernel and C=100
svc=SVC(C=100.0)


# fit classifier to training set
svc.fit(X_train,y_train)

# make predictions on test set
y_pred=svc.predict(X_test)

# compute and print accuracy score
print("Model accuracy score with rbf kernel", (accuracy_score(y_test, y_pred)))

Model accuracy score with rbf kernel 0.7112


In [ ]:
# instantiate classifier with rbf kernel and C=1000
svc=SVC(C=1000.0)


# fit classifier to training set
svc.fit(X_train,y_train)


# make predictions on test set
y_pred=svc.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with rbf kernel and C=1000.0 :',(accuracy_score(y_test, y_pred)))

Model accuracy score with rbf kernel and C=1000.0 : 0.7112


In [ ]:
# instantiate classifier with sigmoid kernel and C=1.0
sigmoid_svc=SVC(kernel='sigmoid', C=1.0)


# fit classifier to training set
sigmoid_svc.fit(X_train,y_train)


# make predictions on test set
y_pred=sigmoid_svc.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with sigmoid kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))


Model accuracy score with sigmoid kernel and C=1.0 : 0.7112
